name: Publish Docs

on:
  push:
    branches: [ main ] # Or your main branch name

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
